server:
  port: 9091
  servlet:
    context-path: /dubboclientexample

dubbo:
  application:
    name: dubboclientexample
    qosEnable: false
  registry:
    id: dubboclientexample-registry
    protocol: multicast
    address: 224.5.6.7
    port: 2181
  scan:
    basePackages: br.com.dubbo.client.example.services
  protocol:
    name: dubbo
  consumer:
    client: netty4
    threads: 200