server:
  port: 9090
spring:
  profiles: local,default
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: null
    driverClassName: org.h2.Driver

dubbo:
  application:
    name: dubboserverexample
    qosEnable: false
  registry:
    id: dubboserverexample-registry
    protocol: multicast
    address: 224.5.6.7
    port: 2181
  scan:
    basePackages: br.com.dubbo.server.example.services
  protocol:
    name: dubbo
    server: netty4
    threads: 200